### ISSUE TITLE
How do I set the input delay for the transfer function

### ISSUE THREAD

**Issue by chenjuncheng00** [python-control/python-control#910] opened 2023-06-09 02:39 UTC
Thanks for this excellent python control library;
In matlab, I can use  tf(num, den, 'InputDelay', T);
How do I achieve the same effect by use python-control?T

**Comment by murrayrm** [comment] 2023-06-09 05:20
Time delays are not currently supported in python-control, but you are welcome to work on this if you would like.  Duplicate of issue #628.

**Closed by murrayrm** 2023-06-09 05:20 UTC
Labels: duplicate
